name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: 107.20.66.234
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/blog-app
            git pull
            docker stop blog-container || true
            docker rm blog-container || true
            docker build -t blog-app .
            docker run -d -p 3000:3000 --name blog-container blog-app
